// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package ledgerdb

import (
	"context"
	"database/sql"
	"time"

	"aivo/internal/sharedkernel"
	"uuid"
)

const accountByID = `-- name: AccountByID :one
SELECT id, restaurant_id, code, name, type, normal_side, postable, created_at
FROM accounts WHERE restaurant_id = $1 AND id = $2
`

type AccountByIDParams struct {
	RestaurantID uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) AccountByID(ctx context.Context, arg AccountByIDParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, accountByID, arg.RestaurantID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.NormalSide,
		&i.Postable,
		&i.CreatedAt,
	)
	return i, err
}

const accountForPurpose = `-- name: AccountForPurpose :one
SELECT account_id FROM ledger_account_map WHERE restaurant_id = $1 AND purpose = $2
`

type AccountForPurposeParams struct {
	RestaurantID uuid.UUID
	Purpose      string
}

func (q *Queries) AccountForPurpose(ctx context.Context, arg AccountForPurposeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, accountForPurpose, arg.RestaurantID, arg.Purpose)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const accountMap = `-- name: AccountMap :many
SELECT m.purpose, m.account_id, a.code
FROM ledger_account_map m JOIN accounts a ON a.id = m.account_id
WHERE m.restaurant_id = $1 ORDER BY m.purpose
`

type AccountMapRow struct {
	Purpose   string
	AccountID uuid.UUID
	Code      string
}

func (q *Queries) AccountMap(ctx context.Context, restaurantID uuid.UUID) ([]AccountMapRow, error) {
	rows, err := q.db.QueryContext(ctx, accountMap, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountMapRow
	for rows.Next() {
		var i AccountMapRow
		if err := rows.Scan(&i.Purpose, &i.AccountID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountPostedCount = `-- name: AccountPostedCount :one
SELECT count(*) FROM journal_lines jl
JOIN journal_documents jd ON jd.id = jl.document_id
WHERE jl.account_id = $1 AND jd.state = 'posted'
`

func (q *Queries) AccountPostedCount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountPostedCount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const accountsByRestaurant = `-- name: AccountsByRestaurant :many
SELECT id, restaurant_id, code, name, type, normal_side, postable, created_at
FROM accounts WHERE restaurant_id = $1 ORDER BY code
`

func (q *Queries) AccountsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, accountsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.NormalSide,
			&i.Postable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costCenterByCode = `-- name: CostCenterByCode :one
SELECT id, restaurant_id, code, name FROM cost_centers
WHERE restaurant_id = $1 AND code = $2
`

type CostCenterByCodeParams struct {
	RestaurantID uuid.UUID
	Code         string
}

func (q *Queries) CostCenterByCode(ctx context.Context, arg CostCenterByCodeParams) (CostCenter, error) {
	row := q.db.QueryRowContext(ctx, costCenterByCode, arg.RestaurantID, arg.Code)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Code,
		&i.Name,
	)
	return i, err
}

const documentByID = `-- name: DocumentByID :one
SELECT id, restaurant_id, kind, state, accounting_date, recorded_at, posted_at,
       cancelled_at, source_kind, source_id, reversal_of, created_by
FROM journal_documents WHERE restaurant_id = $1 AND id = $2
`

type DocumentByIDParams struct {
	RestaurantID uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) DocumentByID(ctx context.Context, arg DocumentByIDParams) (JournalDocument, error) {
	row := q.db.QueryRowContext(ctx, documentByID, arg.RestaurantID, arg.ID)
	var i JournalDocument
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Kind,
		&i.State,
		&i.AccountingDate,
		&i.RecordedAt,
		&i.PostedAt,
		&i.CancelledAt,
		&i.SourceKind,
		&i.SourceID,
		&i.ReversalOf,
		&i.CreatedBy,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, restaurant_id, code, name, type, normal_side, postable)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAccountParams struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Code         string
	Name         string
	Type         string
	NormalSide   string
	Postable     bool
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.RestaurantID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.NormalSide,
		arg.Postable,
	)
	return err
}

const insertCostCenter = `-- name: InsertCostCenter :exec
INSERT INTO cost_centers (id, restaurant_id, code, name) VALUES ($1, $2, $3, $4)
`

type InsertCostCenterParams struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Code         string
	Name         string
}

func (q *Queries) InsertCostCenter(ctx context.Context, arg InsertCostCenterParams) error {
	_, err := q.db.ExecContext(ctx, insertCostCenter,
		arg.ID,
		arg.RestaurantID,
		arg.Code,
		arg.Name,
	)
	return err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO journal_documents
    (id, restaurant_id, kind, state, accounting_date, recorded_at, posted_at,
     cancelled_at, source_kind, source_id, reversal_of, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertDocumentParams struct {
	ID             uuid.UUID
	RestaurantID   uuid.UUID
	Kind           string
	State          string
	AccountingDate time.Time
	RecordedAt     time.Time
	PostedAt       sql.NullTime
	CancelledAt    sql.NullTime
	SourceKind     sql.NullString
	SourceID       sharedkernel.NullID
	ReversalOf     sharedkernel.NullID
	CreatedBy      uuid.UUID
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, insertDocument,
		arg.ID,
		arg.RestaurantID,
		arg.Kind,
		arg.State,
		arg.AccountingDate,
		arg.RecordedAt,
		arg.PostedAt,
		arg.CancelledAt,
		arg.SourceKind,
		arg.SourceID,
		arg.ReversalOf,
		arg.CreatedBy,
	)
	return err
}

const insertLine = `-- name: InsertLine :exec
INSERT INTO journal_lines
    (id, document_id, account_id, side, amount_cents, cost_center_id, memo, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLineParams struct {
	ID           uuid.UUID
	DocumentID   uuid.UUID
	AccountID    uuid.UUID
	Side         string
	AmountCents  int64
	CostCenterID uuid.UUID
	Memo         string
	Seq          int32
}

func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) error {
	_, err := q.db.ExecContext(ctx, insertLine,
		arg.ID,
		arg.DocumentID,
		arg.AccountID,
		arg.Side,
		arg.AmountCents,
		arg.CostCenterID,
		arg.Memo,
		arg.Seq,
	)
	return err
}

const linesForDocument = `-- name: LinesForDocument :many
SELECT id, document_id, account_id, side, amount_cents, cost_center_id, memo, seq
FROM journal_lines WHERE document_id = $1 ORDER BY seq
`

func (q *Queries) LinesForDocument(ctx context.Context, documentID uuid.UUID) ([]JournalLine, error) {
	rows, err := q.db.QueryContext(ctx, linesForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalLine
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AccountID,
			&i.Side,
			&i.AmountCents,
			&i.CostCenterID,
			&i.Memo,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentCancelled = `-- name: MarkDocumentCancelled :exec
UPDATE journal_documents SET state = 'cancelled', cancelled_at = $3
WHERE restaurant_id = $1 AND id = $2 AND state = 'posted'
`

type MarkDocumentCancelledParams struct {
	RestaurantID uuid.UUID
	ID           uuid.UUID
	CancelledAt  sql.NullTime
}

func (q *Queries) MarkDocumentCancelled(ctx context.Context, arg MarkDocumentCancelledParams) error {
	_, err := q.db.ExecContext(ctx, markDocumentCancelled, arg.RestaurantID, arg.ID, arg.CancelledAt)
	return err
}

const markDocumentPosted = `-- name: MarkDocumentPosted :exec
UPDATE journal_documents SET state = 'posted', posted_at = $3
WHERE restaurant_id = $1 AND id = $2 AND state = 'draft'
`

type MarkDocumentPostedParams struct {
	RestaurantID uuid.UUID
	ID           uuid.UUID
	PostedAt     sql.NullTime
}

func (q *Queries) MarkDocumentPosted(ctx context.Context, arg MarkDocumentPostedParams) error {
	_, err := q.db.ExecContext(ctx, markDocumentPosted, arg.RestaurantID, arg.ID, arg.PostedAt)
	return err
}

const postedJournals = `-- name: PostedJournals :many
SELECT id, kind, state, accounting_date, recorded_at, source_kind, source_id, reversal_of
FROM journal_documents
WHERE restaurant_id = $1 AND state = 'posted' AND accounting_date >= $2
ORDER BY accounting_date, recorded_at
`

type PostedJournalsParams struct {
	RestaurantID   uuid.UUID
	AccountingDate time.Time
}

type PostedJournalsRow struct {
	ID             uuid.UUID
	Kind           string
	State          string
	AccountingDate time.Time
	RecordedAt     time.Time
	SourceKind     sql.NullString
	SourceID       sharedkernel.NullID
	ReversalOf     sharedkernel.NullID
}

func (q *Queries) PostedJournals(ctx context.Context, arg PostedJournalsParams) ([]PostedJournalsRow, error) {
	rows, err := q.db.QueryContext(ctx, postedJournals, arg.RestaurantID, arg.AccountingDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostedJournalsRow
	for rows.Next() {
		var i PostedJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.State,
			&i.AccountingDate,
			&i.RecordedAt,
			&i.SourceKind,
			&i.SourceID,
			&i.ReversalOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountMap = `-- name: UpsertAccountMap :exec
INSERT INTO ledger_account_map (restaurant_id, purpose, account_id)
VALUES ($1, $2, $3)
ON CONFLICT (restaurant_id, purpose) DO UPDATE SET account_id = EXCLUDED.account_id
`

type UpsertAccountMapParams struct {
	RestaurantID uuid.UUID
	Purpose      string
	AccountID    uuid.UUID
}

func (q *Queries) UpsertAccountMap(ctx context.Context, arg UpsertAccountMapParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountMap, arg.RestaurantID, arg.Purpose, arg.AccountID)
	return err
}
