// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package platformdb

import (
	"context"
	"encoding/json"
	"time"

	"aivo/internal/sharedkernel"
	"uuid"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, name, aggregate_type, aggregate_id, restaurant_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEventParams struct {
	ID            uuid.UUID
	Name          string
	AggregateType string
	AggregateID   uuid.UUID
	RestaurantID  sharedkernel.NullID
	Payload       json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Name,
		arg.AggregateType,
		arg.AggregateID,
		arg.RestaurantID,
		arg.Payload,
	)
	return err
}

const markEventPublished = `-- name: MarkEventPublished :exec
UPDATE events SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEventPublished, id)
	return err
}

const pendingEvents = `-- name: PendingEvents :many
SELECT id, name, aggregate_type, aggregate_id, restaurant_id, payload, occurred_at
FROM events WHERE published_at IS NULL ORDER BY occurred_at LIMIT $1
`

type PendingEventsRow struct {
	ID            uuid.UUID
	Name          string
	AggregateType string
	AggregateID   uuid.UUID
	RestaurantID  sharedkernel.NullID
	Payload       json.RawMessage
	OccurredAt    time.Time
}

func (q *Queries) PendingEvents(ctx context.Context, limit int32) ([]PendingEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingEventsRow
	for rows.Next() {
		var i PendingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AggregateType,
			&i.AggregateID,
			&i.RestaurantID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, org_id, email, password_hash, role, restaurant_id, created_at
FROM users WHERE email = $1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.RestaurantID,
		&i.CreatedAt,
	)
	return i, err
}
