// service-events / inventory-service capability (see
// openspec/changes/split-inventory-microservice). Request shapes mirror
// what internal/ledger/app's PostInventoryJournal/CancelJournalForSource
// take as arguments today (internal/inventory/ports.Ledger,
// internal/inventory/ports.JournalLine) — inventory calls this once it
// stops calling ledger in-process.
//
// Written by the inventory worktree since it was not present when this
// worktree started (tasks.md 3.3) — svc-server owns the actual
// LedgerService implementation (cmd/aivo-server's :9080 listener,
// tasks.md 6.1); reconcile at merge if svc-server independently authored
// a conflicting version.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_PostCOGSJournal_FullMethodName        = "/ledger.v1.LedgerService/PostCOGSJournal"
	LedgerService_PostReceiptJournal_FullMethodName     = "/ledger.v1.LedgerService/PostReceiptJournal"
	LedgerService_PostWriteOffJournal_FullMethodName    = "/ledger.v1.LedgerService/PostWriteOffJournal"
	LedgerService_PostStocktakeJournal_FullMethodName   = "/ledger.v1.LedgerService/PostStocktakeJournal"
	LedgerService_CancelReceiptJournal_FullMethodName   = "/ledger.v1.LedgerService/CancelReceiptJournal"
	LedgerService_CancelWriteOffJournal_FullMethodName  = "/ledger.v1.LedgerService/CancelWriteOffJournal"
	LedgerService_CancelStocktakeJournal_FullMethodName = "/ledger.v1.LedgerService/CancelStocktakeJournal"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LedgerService is ledger's gRPC inbound for every inventory-originated
// GL posting (sale COGS, receipt, write-off, stocktake, and reversals of
// the latter three) — one bespoke RPC per event, no generic envelope
// (design.md D4).
type LedgerServiceClient interface {
	PostCOGSJournal(ctx context.Context, in *PostCOGSJournalRequest, opts ...grpc.CallOption) (*PostCOGSJournalResponse, error)
	PostReceiptJournal(ctx context.Context, in *PostReceiptJournalRequest, opts ...grpc.CallOption) (*PostReceiptJournalResponse, error)
	PostWriteOffJournal(ctx context.Context, in *PostWriteOffJournalRequest, opts ...grpc.CallOption) (*PostWriteOffJournalResponse, error)
	PostStocktakeJournal(ctx context.Context, in *PostStocktakeJournalRequest, opts ...grpc.CallOption) (*PostStocktakeJournalResponse, error)
	CancelReceiptJournal(ctx context.Context, in *CancelReceiptJournalRequest, opts ...grpc.CallOption) (*CancelReceiptJournalResponse, error)
	CancelWriteOffJournal(ctx context.Context, in *CancelWriteOffJournalRequest, opts ...grpc.CallOption) (*CancelWriteOffJournalResponse, error)
	CancelStocktakeJournal(ctx context.Context, in *CancelStocktakeJournalRequest, opts ...grpc.CallOption) (*CancelStocktakeJournalResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) PostCOGSJournal(ctx context.Context, in *PostCOGSJournalRequest, opts ...grpc.CallOption) (*PostCOGSJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCOGSJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostCOGSJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostReceiptJournal(ctx context.Context, in *PostReceiptJournalRequest, opts ...grpc.CallOption) (*PostReceiptJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostReceiptJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostReceiptJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostWriteOffJournal(ctx context.Context, in *PostWriteOffJournalRequest, opts ...grpc.CallOption) (*PostWriteOffJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostWriteOffJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostWriteOffJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostStocktakeJournal(ctx context.Context, in *PostStocktakeJournalRequest, opts ...grpc.CallOption) (*PostStocktakeJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostStocktakeJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostStocktakeJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) CancelReceiptJournal(ctx context.Context, in *CancelReceiptJournalRequest, opts ...grpc.CallOption) (*CancelReceiptJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelReceiptJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_CancelReceiptJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) CancelWriteOffJournal(ctx context.Context, in *CancelWriteOffJournalRequest, opts ...grpc.CallOption) (*CancelWriteOffJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWriteOffJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_CancelWriteOffJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) CancelStocktakeJournal(ctx context.Context, in *CancelStocktakeJournalRequest, opts ...grpc.CallOption) (*CancelStocktakeJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelStocktakeJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_CancelStocktakeJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
//
// LedgerService is ledger's gRPC inbound for every inventory-originated
// GL posting (sale COGS, receipt, write-off, stocktake, and reversals of
// the latter three) — one bespoke RPC per event, no generic envelope
// (design.md D4).
type LedgerServiceServer interface {
	PostCOGSJournal(context.Context, *PostCOGSJournalRequest) (*PostCOGSJournalResponse, error)
	PostReceiptJournal(context.Context, *PostReceiptJournalRequest) (*PostReceiptJournalResponse, error)
	PostWriteOffJournal(context.Context, *PostWriteOffJournalRequest) (*PostWriteOffJournalResponse, error)
	PostStocktakeJournal(context.Context, *PostStocktakeJournalRequest) (*PostStocktakeJournalResponse, error)
	CancelReceiptJournal(context.Context, *CancelReceiptJournalRequest) (*CancelReceiptJournalResponse, error)
	CancelWriteOffJournal(context.Context, *CancelWriteOffJournalRequest) (*CancelWriteOffJournalResponse, error)
	CancelStocktakeJournal(context.Context, *CancelStocktakeJournalRequest) (*CancelStocktakeJournalResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) PostCOGSJournal(context.Context, *PostCOGSJournalRequest) (*PostCOGSJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostCOGSJournal not implemented")
}
func (UnimplementedLedgerServiceServer) PostReceiptJournal(context.Context, *PostReceiptJournalRequest) (*PostReceiptJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostReceiptJournal not implemented")
}
func (UnimplementedLedgerServiceServer) PostWriteOffJournal(context.Context, *PostWriteOffJournalRequest) (*PostWriteOffJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostWriteOffJournal not implemented")
}
func (UnimplementedLedgerServiceServer) PostStocktakeJournal(context.Context, *PostStocktakeJournalRequest) (*PostStocktakeJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostStocktakeJournal not implemented")
}
func (UnimplementedLedgerServiceServer) CancelReceiptJournal(context.Context, *CancelReceiptJournalRequest) (*CancelReceiptJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelReceiptJournal not implemented")
}
func (UnimplementedLedgerServiceServer) CancelWriteOffJournal(context.Context, *CancelWriteOffJournalRequest) (*CancelWriteOffJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelWriteOffJournal not implemented")
}
func (UnimplementedLedgerServiceServer) CancelStocktakeJournal(context.Context, *CancelStocktakeJournalRequest) (*CancelStocktakeJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelStocktakeJournal not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_PostCOGSJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCOGSJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostCOGSJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostCOGSJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostCOGSJournal(ctx, req.(*PostCOGSJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostReceiptJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostReceiptJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostReceiptJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostReceiptJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostReceiptJournal(ctx, req.(*PostReceiptJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostWriteOffJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostWriteOffJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostWriteOffJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostWriteOffJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostWriteOffJournal(ctx, req.(*PostWriteOffJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostStocktakeJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStocktakeJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostStocktakeJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostStocktakeJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostStocktakeJournal(ctx, req.(*PostStocktakeJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_CancelReceiptJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReceiptJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CancelReceiptJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CancelReceiptJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CancelReceiptJournal(ctx, req.(*CancelReceiptJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_CancelWriteOffJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWriteOffJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CancelWriteOffJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CancelWriteOffJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CancelWriteOffJournal(ctx, req.(*CancelWriteOffJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_CancelStocktakeJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelStocktakeJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CancelStocktakeJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CancelStocktakeJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CancelStocktakeJournal(ctx, req.(*CancelStocktakeJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostCOGSJournal",
			Handler:    _LedgerService_PostCOGSJournal_Handler,
		},
		{
			MethodName: "PostReceiptJournal",
			Handler:    _LedgerService_PostReceiptJournal_Handler,
		},
		{
			MethodName: "PostWriteOffJournal",
			Handler:    _LedgerService_PostWriteOffJournal_Handler,
		},
		{
			MethodName: "PostStocktakeJournal",
			Handler:    _LedgerService_PostStocktakeJournal_Handler,
		},
		{
			MethodName: "CancelReceiptJournal",
			Handler:    _LedgerService_CancelReceiptJournal_Handler,
		},
		{
			MethodName: "CancelWriteOffJournal",
			Handler:    _LedgerService_CancelWriteOffJournal_Handler,
		},
		{
			MethodName: "CancelStocktakeJournal",
			Handler:    _LedgerService_CancelStocktakeJournal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger/v1/ledger.proto",
}
