// service-events / inventory-service capability (see
// openspec/changes/split-inventory-microservice). Request shapes mirror
// what internal/ledger/app's PostInventoryJournal/CancelJournalForSource
// take as arguments today (internal/inventory/ports.Ledger,
// internal/inventory/ports.JournalLine) — inventory calls this once it
// stops calling ledger in-process.
//
// Written by the inventory worktree since it was not present when this
// worktree started (tasks.md 3.3) — svc-server owns the actual
// LedgerService implementation (cmd/aivo-server's :9080 listener,
// tasks.md 6.1); reconcile at merge if svc-server independently authored
// a conflicting version.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JournalLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"` // "debit" | "credit"
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalLine) Reset() {
	*x = JournalLine{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalLine) ProtoMessage() {}

func (x *JournalLine) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalLine.ProtoReflect.Descriptor instead.
func (*JournalLine) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *JournalLine) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *JournalLine) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *JournalLine) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

// PostCOGSJournalRequest and the other three Post*JournalRequest messages
// are structurally identical (design.md D3: idempotency key = the
// existing domain document id) — kept as separate messages per RPC to
// satisfy buf's standard lint ruleset (one request/response pair per
// RPC), not because their fields differ.
type PostCOGSJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`       // uuid
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`                // uuid
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`                   // uuid; idempotency key (ticket id)
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"` // YYYY-MM-DD
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostCOGSJournalRequest) Reset() {
	*x = PostCOGSJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCOGSJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCOGSJournalRequest) ProtoMessage() {}

func (x *PostCOGSJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCOGSJournalRequest.ProtoReflect.Descriptor instead.
func (*PostCOGSJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *PostCOGSJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostCOGSJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"` // uuid of the posted GL journal (or the existing one, on a no-op redelivery)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCOGSJournalResponse) Reset() {
	*x = PostCOGSJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCOGSJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCOGSJournalResponse) ProtoMessage() {}

func (x *PostCOGSJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCOGSJournalResponse.ProtoReflect.Descriptor instead.
func (*PostCOGSJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *PostCOGSJournalResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type PostReceiptJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // receipt id
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"`
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostReceiptJournalRequest) Reset() {
	*x = PostReceiptJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReceiptJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReceiptJournalRequest) ProtoMessage() {}

func (x *PostReceiptJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReceiptJournalRequest.ProtoReflect.Descriptor instead.
func (*PostReceiptJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *PostReceiptJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostReceiptJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReceiptJournalResponse) Reset() {
	*x = PostReceiptJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReceiptJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReceiptJournalResponse) ProtoMessage() {}

func (x *PostReceiptJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReceiptJournalResponse.ProtoReflect.Descriptor instead.
func (*PostReceiptJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *PostReceiptJournalResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type PostWriteOffJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // write-off id
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"`
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostWriteOffJournalRequest) Reset() {
	*x = PostWriteOffJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostWriteOffJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostWriteOffJournalRequest) ProtoMessage() {}

func (x *PostWriteOffJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostWriteOffJournalRequest.ProtoReflect.Descriptor instead.
func (*PostWriteOffJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *PostWriteOffJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostWriteOffJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostWriteOffJournalResponse) Reset() {
	*x = PostWriteOffJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostWriteOffJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostWriteOffJournalResponse) ProtoMessage() {}

func (x *PostWriteOffJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostWriteOffJournalResponse.ProtoReflect.Descriptor instead.
func (*PostWriteOffJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *PostWriteOffJournalResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type PostStocktakeJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // stocktake id
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"`
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostStocktakeJournalRequest) Reset() {
	*x = PostStocktakeJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStocktakeJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStocktakeJournalRequest) ProtoMessage() {}

func (x *PostStocktakeJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStocktakeJournalRequest.ProtoReflect.Descriptor instead.
func (*PostStocktakeJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *PostStocktakeJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostStocktakeJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStocktakeJournalResponse) Reset() {
	*x = PostStocktakeJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStocktakeJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStocktakeJournalResponse) ProtoMessage() {}

func (x *PostStocktakeJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStocktakeJournalResponse.ProtoReflect.Descriptor instead.
func (*PostStocktakeJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *PostStocktakeJournalResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type CancelReceiptJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // the original receipt's id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReceiptJournalRequest) Reset() {
	*x = CancelReceiptJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReceiptJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReceiptJournalRequest) ProtoMessage() {}

func (x *CancelReceiptJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReceiptJournalRequest.ProtoReflect.Descriptor instead.
func (*CancelReceiptJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *CancelReceiptJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *CancelReceiptJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CancelReceiptJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReversalId    string                 `protobuf:"bytes,1,opt,name=reversal_id,json=reversalId,proto3" json:"reversal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReceiptJournalResponse) Reset() {
	*x = CancelReceiptJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReceiptJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReceiptJournalResponse) ProtoMessage() {}

func (x *CancelReceiptJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReceiptJournalResponse.ProtoReflect.Descriptor instead.
func (*CancelReceiptJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *CancelReceiptJournalResponse) GetReversalId() string {
	if x != nil {
		return x.ReversalId
	}
	return ""
}

type CancelWriteOffJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWriteOffJournalRequest) Reset() {
	*x = CancelWriteOffJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWriteOffJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWriteOffJournalRequest) ProtoMessage() {}

func (x *CancelWriteOffJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWriteOffJournalRequest.ProtoReflect.Descriptor instead.
func (*CancelWriteOffJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *CancelWriteOffJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *CancelWriteOffJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CancelWriteOffJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReversalId    string                 `protobuf:"bytes,1,opt,name=reversal_id,json=reversalId,proto3" json:"reversal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWriteOffJournalResponse) Reset() {
	*x = CancelWriteOffJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWriteOffJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWriteOffJournalResponse) ProtoMessage() {}

func (x *CancelWriteOffJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWriteOffJournalResponse.ProtoReflect.Descriptor instead.
func (*CancelWriteOffJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *CancelWriteOffJournalResponse) GetReversalId() string {
	if x != nil {
		return x.ReversalId
	}
	return ""
}

type CancelStocktakeJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStocktakeJournalRequest) Reset() {
	*x = CancelStocktakeJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStocktakeJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStocktakeJournalRequest) ProtoMessage() {}

func (x *CancelStocktakeJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStocktakeJournalRequest.ProtoReflect.Descriptor instead.
func (*CancelStocktakeJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *CancelStocktakeJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *CancelStocktakeJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CancelStocktakeJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReversalId    string                 `protobuf:"bytes,1,opt,name=reversal_id,json=reversalId,proto3" json:"reversal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStocktakeJournalResponse) Reset() {
	*x = CancelStocktakeJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStocktakeJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStocktakeJournalResponse) ProtoMessage() {}

func (x *CancelStocktakeJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStocktakeJournalResponse.ProtoReflect.Descriptor instead.
func (*CancelStocktakeJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *CancelStocktakeJournalResponse) GetReversalId() string {
	if x != nil {
		return x.ReversalId
	}
	return ""
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\"^\n" +
	"\vJournalLine\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\"\xd0\x01\n" +
	"\x16PostCOGSJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"0\n" +
	"\x17PostCOGSJournalResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"\xd3\x01\n" +
	"\x19PostReceiptJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"3\n" +
	"\x1aPostReceiptJournalResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"\xd4\x01\n" +
	"\x1aPostWriteOffJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"4\n" +
	"\x1bPostWriteOffJournalResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"\xd5\x01\n" +
	"\x1bPostStocktakeJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"5\n" +
	"\x1cPostStocktakeJournalResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"_\n" +
	"\x1bCancelReceiptJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\"?\n" +
	"\x1cCancelReceiptJournalResponse\x12\x1f\n" +
	"\vreversal_id\x18\x01 \x01(\tR\n" +
	"reversalId\"`\n" +
	"\x1cCancelWriteOffJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\"@\n" +
	"\x1dCancelWriteOffJournalResponse\x12\x1f\n" +
	"\vreversal_id\x18\x01 \x01(\tR\n" +
	"reversalId\"a\n" +
	"\x1dCancelStocktakeJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\"A\n" +
	"\x1eCancelStocktakeJournalResponse\x12\x1f\n" +
	"\vreversal_id\x18\x01 \x01(\tR\n" +
	"reversalId2\xdf\x05\n" +
	"\rLedgerService\x12X\n" +
	"\x0fPostCOGSJournal\x12!.ledger.v1.PostCOGSJournalRequest\x1a\".ledger.v1.PostCOGSJournalResponse\x12a\n" +
	"\x12PostReceiptJournal\x12$.ledger.v1.PostReceiptJournalRequest\x1a%.ledger.v1.PostReceiptJournalResponse\x12d\n" +
	"\x13PostWriteOffJournal\x12%.ledger.v1.PostWriteOffJournalRequest\x1a&.ledger.v1.PostWriteOffJournalResponse\x12g\n" +
	"\x14PostStocktakeJournal\x12&.ledger.v1.PostStocktakeJournalRequest\x1a'.ledger.v1.PostStocktakeJournalResponse\x12g\n" +
	"\x14CancelReceiptJournal\x12&.ledger.v1.CancelReceiptJournalRequest\x1a'.ledger.v1.CancelReceiptJournalResponse\x12j\n" +
	"\x15CancelWriteOffJournal\x12'.ledger.v1.CancelWriteOffJournalRequest\x1a(.ledger.v1.CancelWriteOffJournalResponse\x12m\n" +
	"\x16CancelStocktakeJournal\x12(.ledger.v1.CancelStocktakeJournalRequest\x1a).ledger.v1.CancelStocktakeJournalResponseB\"Z aivo/internal/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(*JournalLine)(nil),                    // 0: ledger.v1.JournalLine
	(*PostCOGSJournalRequest)(nil),         // 1: ledger.v1.PostCOGSJournalRequest
	(*PostCOGSJournalResponse)(nil),        // 2: ledger.v1.PostCOGSJournalResponse
	(*PostReceiptJournalRequest)(nil),      // 3: ledger.v1.PostReceiptJournalRequest
	(*PostReceiptJournalResponse)(nil),     // 4: ledger.v1.PostReceiptJournalResponse
	(*PostWriteOffJournalRequest)(nil),     // 5: ledger.v1.PostWriteOffJournalRequest
	(*PostWriteOffJournalResponse)(nil),    // 6: ledger.v1.PostWriteOffJournalResponse
	(*PostStocktakeJournalRequest)(nil),    // 7: ledger.v1.PostStocktakeJournalRequest
	(*PostStocktakeJournalResponse)(nil),   // 8: ledger.v1.PostStocktakeJournalResponse
	(*CancelReceiptJournalRequest)(nil),    // 9: ledger.v1.CancelReceiptJournalRequest
	(*CancelReceiptJournalResponse)(nil),   // 10: ledger.v1.CancelReceiptJournalResponse
	(*CancelWriteOffJournalRequest)(nil),   // 11: ledger.v1.CancelWriteOffJournalRequest
	(*CancelWriteOffJournalResponse)(nil),  // 12: ledger.v1.CancelWriteOffJournalResponse
	(*CancelStocktakeJournalRequest)(nil),  // 13: ledger.v1.CancelStocktakeJournalRequest
	(*CancelStocktakeJournalResponse)(nil), // 14: ledger.v1.CancelStocktakeJournalResponse
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.v1.PostCOGSJournalRequest.lines:type_name -> ledger.v1.JournalLine
	0,  // 1: ledger.v1.PostReceiptJournalRequest.lines:type_name -> ledger.v1.JournalLine
	0,  // 2: ledger.v1.PostWriteOffJournalRequest.lines:type_name -> ledger.v1.JournalLine
	0,  // 3: ledger.v1.PostStocktakeJournalRequest.lines:type_name -> ledger.v1.JournalLine
	1,  // 4: ledger.v1.LedgerService.PostCOGSJournal:input_type -> ledger.v1.PostCOGSJournalRequest
	3,  // 5: ledger.v1.LedgerService.PostReceiptJournal:input_type -> ledger.v1.PostReceiptJournalRequest
	5,  // 6: ledger.v1.LedgerService.PostWriteOffJournal:input_type -> ledger.v1.PostWriteOffJournalRequest
	7,  // 7: ledger.v1.LedgerService.PostStocktakeJournal:input_type -> ledger.v1.PostStocktakeJournalRequest
	9,  // 8: ledger.v1.LedgerService.CancelReceiptJournal:input_type -> ledger.v1.CancelReceiptJournalRequest
	11, // 9: ledger.v1.LedgerService.CancelWriteOffJournal:input_type -> ledger.v1.CancelWriteOffJournalRequest
	13, // 10: ledger.v1.LedgerService.CancelStocktakeJournal:input_type -> ledger.v1.CancelStocktakeJournalRequest
	2,  // 11: ledger.v1.LedgerService.PostCOGSJournal:output_type -> ledger.v1.PostCOGSJournalResponse
	4,  // 12: ledger.v1.LedgerService.PostReceiptJournal:output_type -> ledger.v1.PostReceiptJournalResponse
	6,  // 13: ledger.v1.LedgerService.PostWriteOffJournal:output_type -> ledger.v1.PostWriteOffJournalResponse
	8,  // 14: ledger.v1.LedgerService.PostStocktakeJournal:output_type -> ledger.v1.PostStocktakeJournalResponse
	10, // 15: ledger.v1.LedgerService.CancelReceiptJournal:output_type -> ledger.v1.CancelReceiptJournalResponse
	12, // 16: ledger.v1.LedgerService.CancelWriteOffJournal:output_type -> ledger.v1.CancelWriteOffJournalResponse
	14, // 17: ledger.v1.LedgerService.CancelStocktakeJournal:output_type -> ledger.v1.CancelStocktakeJournalResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
