// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_PostCOGSJournal_FullMethodName         = "/ledger.v1.LedgerService/PostCOGSJournal"
	LedgerService_ReverseCOGSJournal_FullMethodName      = "/ledger.v1.LedgerService/ReverseCOGSJournal"
	LedgerService_PostReceiptJournal_FullMethodName      = "/ledger.v1.LedgerService/PostReceiptJournal"
	LedgerService_ReverseReceiptJournal_FullMethodName   = "/ledger.v1.LedgerService/ReverseReceiptJournal"
	LedgerService_PostWriteOffJournal_FullMethodName     = "/ledger.v1.LedgerService/PostWriteOffJournal"
	LedgerService_ReverseWriteOffJournal_FullMethodName  = "/ledger.v1.LedgerService/ReverseWriteOffJournal"
	LedgerService_PostStocktakeJournal_FullMethodName    = "/ledger.v1.LedgerService/PostStocktakeJournal"
	LedgerService_ReverseStocktakeJournal_FullMethodName = "/ledger.v1.LedgerService/ReverseStocktakeJournal"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LedgerService is cmd/aivo-server's inbound gRPC surface for inventory's
// outbox: every inventory-originated GL posting (sale COGS, receipt,
// write-off, stocktake, and their reversals) crosses this boundary since
// ledger stays in-process for pos but not for inventory (see
// openspec/changes/split-inventory-microservice). Every RPC MUST be
// idempotent on its request's source id (the existing domain document
// id), since delivery is at-least-once.
type LedgerServiceClient interface {
	PostCOGSJournal(ctx context.Context, in *PostCOGSJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error)
	ReverseCOGSJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error)
	PostReceiptJournal(ctx context.Context, in *PostReceiptJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error)
	ReverseReceiptJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error)
	PostWriteOffJournal(ctx context.Context, in *PostWriteOffJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error)
	ReverseWriteOffJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error)
	PostStocktakeJournal(ctx context.Context, in *PostStocktakeJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error)
	ReverseStocktakeJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) PostCOGSJournal(ctx context.Context, in *PostCOGSJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostCOGSJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReverseCOGSJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReverseCOGSJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostReceiptJournal(ctx context.Context, in *PostReceiptJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostReceiptJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReverseReceiptJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReverseReceiptJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostWriteOffJournal(ctx context.Context, in *PostWriteOffJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostWriteOffJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReverseWriteOffJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReverseWriteOffJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostStocktakeJournal(ctx context.Context, in *PostStocktakeJournalRequest, opts ...grpc.CallOption) (*PostJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostStocktakeJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReverseStocktakeJournal(ctx context.Context, in *ReverseJournalRequest, opts ...grpc.CallOption) (*ReverseJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseJournalResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReverseStocktakeJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
//
// LedgerService is cmd/aivo-server's inbound gRPC surface for inventory's
// outbox: every inventory-originated GL posting (sale COGS, receipt,
// write-off, stocktake, and their reversals) crosses this boundary since
// ledger stays in-process for pos but not for inventory (see
// openspec/changes/split-inventory-microservice). Every RPC MUST be
// idempotent on its request's source id (the existing domain document
// id), since delivery is at-least-once.
type LedgerServiceServer interface {
	PostCOGSJournal(context.Context, *PostCOGSJournalRequest) (*PostJournalResponse, error)
	ReverseCOGSJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error)
	PostReceiptJournal(context.Context, *PostReceiptJournalRequest) (*PostJournalResponse, error)
	ReverseReceiptJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error)
	PostWriteOffJournal(context.Context, *PostWriteOffJournalRequest) (*PostJournalResponse, error)
	ReverseWriteOffJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error)
	PostStocktakeJournal(context.Context, *PostStocktakeJournalRequest) (*PostJournalResponse, error)
	ReverseStocktakeJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) PostCOGSJournal(context.Context, *PostCOGSJournalRequest) (*PostJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostCOGSJournal not implemented")
}
func (UnimplementedLedgerServiceServer) ReverseCOGSJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseCOGSJournal not implemented")
}
func (UnimplementedLedgerServiceServer) PostReceiptJournal(context.Context, *PostReceiptJournalRequest) (*PostJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostReceiptJournal not implemented")
}
func (UnimplementedLedgerServiceServer) ReverseReceiptJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseReceiptJournal not implemented")
}
func (UnimplementedLedgerServiceServer) PostWriteOffJournal(context.Context, *PostWriteOffJournalRequest) (*PostJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostWriteOffJournal not implemented")
}
func (UnimplementedLedgerServiceServer) ReverseWriteOffJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseWriteOffJournal not implemented")
}
func (UnimplementedLedgerServiceServer) PostStocktakeJournal(context.Context, *PostStocktakeJournalRequest) (*PostJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostStocktakeJournal not implemented")
}
func (UnimplementedLedgerServiceServer) ReverseStocktakeJournal(context.Context, *ReverseJournalRequest) (*ReverseJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseStocktakeJournal not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_PostCOGSJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCOGSJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostCOGSJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostCOGSJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostCOGSJournal(ctx, req.(*PostCOGSJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReverseCOGSJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReverseCOGSJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReverseCOGSJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReverseCOGSJournal(ctx, req.(*ReverseJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostReceiptJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostReceiptJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostReceiptJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostReceiptJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostReceiptJournal(ctx, req.(*PostReceiptJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReverseReceiptJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReverseReceiptJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReverseReceiptJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReverseReceiptJournal(ctx, req.(*ReverseJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostWriteOffJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostWriteOffJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostWriteOffJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostWriteOffJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostWriteOffJournal(ctx, req.(*PostWriteOffJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReverseWriteOffJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReverseWriteOffJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReverseWriteOffJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReverseWriteOffJournal(ctx, req.(*ReverseJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostStocktakeJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStocktakeJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostStocktakeJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostStocktakeJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostStocktakeJournal(ctx, req.(*PostStocktakeJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReverseStocktakeJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReverseStocktakeJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReverseStocktakeJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReverseStocktakeJournal(ctx, req.(*ReverseJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostCOGSJournal",
			Handler:    _LedgerService_PostCOGSJournal_Handler,
		},
		{
			MethodName: "ReverseCOGSJournal",
			Handler:    _LedgerService_ReverseCOGSJournal_Handler,
		},
		{
			MethodName: "PostReceiptJournal",
			Handler:    _LedgerService_PostReceiptJournal_Handler,
		},
		{
			MethodName: "ReverseReceiptJournal",
			Handler:    _LedgerService_ReverseReceiptJournal_Handler,
		},
		{
			MethodName: "PostWriteOffJournal",
			Handler:    _LedgerService_PostWriteOffJournal_Handler,
		},
		{
			MethodName: "ReverseWriteOffJournal",
			Handler:    _LedgerService_ReverseWriteOffJournal_Handler,
		},
		{
			MethodName: "PostStocktakeJournal",
			Handler:    _LedgerService_PostStocktakeJournal_Handler,
		},
		{
			MethodName: "ReverseStocktakeJournal",
			Handler:    _LedgerService_ReverseStocktakeJournal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger/v1/ledger.proto",
}
