// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JournalLine mirrors internal/ledger/app.InventoryJournalLine: one line
// of an inventory-originated GL document, addressed by purpose (resolved
// through the restaurant's ledger_account_map).
type JournalLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"` // e.g. "cogs", "inventory", "accounts_payable", "inventory_shrinkage", "inventory_surplus"
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`       // "debit" | "credit"
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalLine) Reset() {
	*x = JournalLine{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalLine) ProtoMessage() {}

func (x *JournalLine) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalLine.ProtoReflect.Descriptor instead.
func (*JournalLine) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *JournalLine) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *JournalLine) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *JournalLine) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type PostCOGSJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`       // uuid
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`                // uuid
	TicketId       string                 `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`                   // uuid; idempotency key (source document id)
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"` // YYYY-MM-DD
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostCOGSJournalRequest) Reset() {
	*x = PostCOGSJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCOGSJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCOGSJournalRequest) ProtoMessage() {}

func (x *PostCOGSJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCOGSJournalRequest.ProtoReflect.Descriptor instead.
func (*PostCOGSJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *PostCOGSJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostCOGSJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostReceiptJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ReceiptId      string                 `protobuf:"bytes,3,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"` // idempotency key
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"`
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostReceiptJournalRequest) Reset() {
	*x = PostReceiptJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReceiptJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReceiptJournalRequest) ProtoMessage() {}

func (x *PostReceiptJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReceiptJournalRequest.ProtoReflect.Descriptor instead.
func (*PostReceiptJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *PostReceiptJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostReceiptJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostWriteOffJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	WriteOffId     string                 `protobuf:"bytes,3,opt,name=write_off_id,json=writeOffId,proto3" json:"write_off_id,omitempty"` // idempotency key
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"`
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostWriteOffJournalRequest) Reset() {
	*x = PostWriteOffJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostWriteOffJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostWriteOffJournalRequest) ProtoMessage() {}

func (x *PostWriteOffJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostWriteOffJournalRequest.ProtoReflect.Descriptor instead.
func (*PostWriteOffJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *PostWriteOffJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetWriteOffId() string {
	if x != nil {
		return x.WriteOffId
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostWriteOffJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PostStocktakeJournalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId   string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	StocktakeId    string                 `protobuf:"bytes,3,opt,name=stocktake_id,json=stocktakeId,proto3" json:"stocktake_id,omitempty"` // idempotency key
	AccountingDate string                 `protobuf:"bytes,4,opt,name=accounting_date,json=accountingDate,proto3" json:"accounting_date,omitempty"`
	Lines          []*JournalLine         `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostStocktakeJournalRequest) Reset() {
	*x = PostStocktakeJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStocktakeJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStocktakeJournalRequest) ProtoMessage() {}

func (x *PostStocktakeJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStocktakeJournalRequest.ProtoReflect.Descriptor instead.
func (*PostStocktakeJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *PostStocktakeJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetStocktakeId() string {
	if x != nil {
		return x.StocktakeId
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetAccountingDate() string {
	if x != nil {
		return x.AccountingDate
	}
	return ""
}

func (x *PostStocktakeJournalRequest) GetLines() []*JournalLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

// PostJournalResponse is shared by every Post* RPC: the posted (or,
// on a redelivery, the already-posted) document's id.
type PostJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostJournalResponse) Reset() {
	*x = PostJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostJournalResponse) ProtoMessage() {}

func (x *PostJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostJournalResponse.ProtoReflect.Descriptor instead.
func (*PostJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *PostJournalResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// ReverseJournalRequest is shared by every Reverse* RPC: restaurant_id
// plus the original document's source id (same id used to post it).
type ReverseJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseJournalRequest) Reset() {
	*x = ReverseJournalRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseJournalRequest) ProtoMessage() {}

func (x *ReverseJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseJournalRequest.ProtoReflect.Descriptor instead.
func (*ReverseJournalRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *ReverseJournalRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *ReverseJournalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

// ReverseJournalResponse is shared by every Reverse* RPC: the reversal
// (or, on a redelivery, the already-created reversal) document's id.
type ReverseJournalResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReversalDocumentId string                 `protobuf:"bytes,1,opt,name=reversal_document_id,json=reversalDocumentId,proto3" json:"reversal_document_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReverseJournalResponse) Reset() {
	*x = ReverseJournalResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseJournalResponse) ProtoMessage() {}

func (x *ReverseJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseJournalResponse.ProtoReflect.Descriptor instead.
func (*ReverseJournalResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *ReverseJournalResponse) GetReversalDocumentId() string {
	if x != nil {
		return x.ReversalDocumentId
	}
	return ""
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\"^\n" +
	"\vJournalLine\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\"\xd0\x01\n" +
	"\x16PostCOGSJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\tR\bticketId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"\xd5\x01\n" +
	"\x19PostReceiptJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x03 \x01(\tR\treceiptId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"\xd9\x01\n" +
	"\x1aPostWriteOffJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12 \n" +
	"\fwrite_off_id\x18\x03 \x01(\tR\n" +
	"writeOffId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"\xdb\x01\n" +
	"\x1bPostStocktakeJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12!\n" +
	"\fstocktake_id\x18\x03 \x01(\tR\vstocktakeId\x12'\n" +
	"\x0faccounting_date\x18\x04 \x01(\tR\x0eaccountingDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.ledger.v1.JournalLineR\x05lines\"6\n" +
	"\x13PostJournalResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"Y\n" +
	"\x15ReverseJournalRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\"J\n" +
	"\x16ReverseJournalResponse\x120\n" +
	"\x14reversal_document_id\x18\x01 \x01(\tR\x12reversalDocumentId2\xf7\x05\n" +
	"\rLedgerService\x12T\n" +
	"\x0fPostCOGSJournal\x12!.ledger.v1.PostCOGSJournalRequest\x1a\x1e.ledger.v1.PostJournalResponse\x12Y\n" +
	"\x12ReverseCOGSJournal\x12 .ledger.v1.ReverseJournalRequest\x1a!.ledger.v1.ReverseJournalResponse\x12Z\n" +
	"\x12PostReceiptJournal\x12$.ledger.v1.PostReceiptJournalRequest\x1a\x1e.ledger.v1.PostJournalResponse\x12\\\n" +
	"\x15ReverseReceiptJournal\x12 .ledger.v1.ReverseJournalRequest\x1a!.ledger.v1.ReverseJournalResponse\x12\\\n" +
	"\x13PostWriteOffJournal\x12%.ledger.v1.PostWriteOffJournalRequest\x1a\x1e.ledger.v1.PostJournalResponse\x12]\n" +
	"\x16ReverseWriteOffJournal\x12 .ledger.v1.ReverseJournalRequest\x1a!.ledger.v1.ReverseJournalResponse\x12^\n" +
	"\x14PostStocktakeJournal\x12&.ledger.v1.PostStocktakeJournalRequest\x1a\x1e.ledger.v1.PostJournalResponse\x12^\n" +
	"\x17ReverseStocktakeJournal\x12 .ledger.v1.ReverseJournalRequest\x1a!.ledger.v1.ReverseJournalResponseB\"Z aivo/internal/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(*JournalLine)(nil),                 // 0: ledger.v1.JournalLine
	(*PostCOGSJournalRequest)(nil),      // 1: ledger.v1.PostCOGSJournalRequest
	(*PostReceiptJournalRequest)(nil),   // 2: ledger.v1.PostReceiptJournalRequest
	(*PostWriteOffJournalRequest)(nil),  // 3: ledger.v1.PostWriteOffJournalRequest
	(*PostStocktakeJournalRequest)(nil), // 4: ledger.v1.PostStocktakeJournalRequest
	(*PostJournalResponse)(nil),         // 5: ledger.v1.PostJournalResponse
	(*ReverseJournalRequest)(nil),       // 6: ledger.v1.ReverseJournalRequest
	(*ReverseJournalResponse)(nil),      // 7: ledger.v1.ReverseJournalResponse
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.v1.PostCOGSJournalRequest.lines:type_name -> ledger.v1.JournalLine
	0,  // 1: ledger.v1.PostReceiptJournalRequest.lines:type_name -> ledger.v1.JournalLine
	0,  // 2: ledger.v1.PostWriteOffJournalRequest.lines:type_name -> ledger.v1.JournalLine
	0,  // 3: ledger.v1.PostStocktakeJournalRequest.lines:type_name -> ledger.v1.JournalLine
	1,  // 4: ledger.v1.LedgerService.PostCOGSJournal:input_type -> ledger.v1.PostCOGSJournalRequest
	6,  // 5: ledger.v1.LedgerService.ReverseCOGSJournal:input_type -> ledger.v1.ReverseJournalRequest
	2,  // 6: ledger.v1.LedgerService.PostReceiptJournal:input_type -> ledger.v1.PostReceiptJournalRequest
	6,  // 7: ledger.v1.LedgerService.ReverseReceiptJournal:input_type -> ledger.v1.ReverseJournalRequest
	3,  // 8: ledger.v1.LedgerService.PostWriteOffJournal:input_type -> ledger.v1.PostWriteOffJournalRequest
	6,  // 9: ledger.v1.LedgerService.ReverseWriteOffJournal:input_type -> ledger.v1.ReverseJournalRequest
	4,  // 10: ledger.v1.LedgerService.PostStocktakeJournal:input_type -> ledger.v1.PostStocktakeJournalRequest
	6,  // 11: ledger.v1.LedgerService.ReverseStocktakeJournal:input_type -> ledger.v1.ReverseJournalRequest
	5,  // 12: ledger.v1.LedgerService.PostCOGSJournal:output_type -> ledger.v1.PostJournalResponse
	7,  // 13: ledger.v1.LedgerService.ReverseCOGSJournal:output_type -> ledger.v1.ReverseJournalResponse
	5,  // 14: ledger.v1.LedgerService.PostReceiptJournal:output_type -> ledger.v1.PostJournalResponse
	7,  // 15: ledger.v1.LedgerService.ReverseReceiptJournal:output_type -> ledger.v1.ReverseJournalResponse
	5,  // 16: ledger.v1.LedgerService.PostWriteOffJournal:output_type -> ledger.v1.PostJournalResponse
	7,  // 17: ledger.v1.LedgerService.ReverseWriteOffJournal:output_type -> ledger.v1.ReverseJournalResponse
	5,  // 18: ledger.v1.LedgerService.PostStocktakeJournal:output_type -> ledger.v1.PostJournalResponse
	7,  // 19: ledger.v1.LedgerService.ReverseStocktakeJournal:output_type -> ledger.v1.ReverseJournalResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
