// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package inventorydb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"aivo/internal/sharedkernel"
	"uuid"
)

const activeTechCard = `-- name: ActiveTechCard :one
SELECT id, restaurant_id, product_id, valid_from, valid_to, consumption, yield_milli, created_by, created_at
FROM tech_cards
WHERE restaurant_id = $1 AND product_id = $2 AND valid_from <= $3 AND (valid_to IS NULL OR valid_to > $3)
`

type ActiveTechCardParams struct {
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
	ValidFrom    time.Time
}

func (q *Queries) ActiveTechCard(ctx context.Context, arg ActiveTechCardParams) (TechCard, error) {
	row := q.db.QueryRowContext(ctx, activeTechCard, arg.RestaurantID, arg.ProductID, arg.ValidFrom)
	var i TechCard
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.ProductID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Consumption,
		&i.YieldMilli,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const closeTechCard = `-- name: CloseTechCard :exec
UPDATE tech_cards SET valid_to = $2 WHERE id = $1
`

type CloseTechCardParams struct {
	ID      uuid.UUID
	ValidTo sql.NullTime
}

func (q *Queries) CloseTechCard(ctx context.Context, arg CloseTechCardParams) error {
	_, err := q.db.ExecContext(ctx, closeTechCard, arg.ID, arg.ValidTo)
	return err
}

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO inventory_products (id, restaurant_id, sku, name, type, stock_unit, menu_item_id, min_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertProductParams struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Sku          string
	Name         string
	Type         string
	StockUnit    string
	MenuItemID   sharedkernel.NullID
	MinStock     sql.NullInt64
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.ExecContext(ctx, insertProduct,
		arg.ID,
		arg.RestaurantID,
		arg.Sku,
		arg.Name,
		arg.Type,
		arg.StockUnit,
		arg.MenuItemID,
		arg.MinStock,
	)
	return err
}

const insertReceipt = `-- name: InsertReceipt :exec
INSERT INTO goods_receipts (id, restaurant_id, supplier_id, status, business_date, note, reversal_of)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertReceiptParams struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	SupplierID   sharedkernel.NullID
	Status       string
	BusinessDate time.Time
	Note         string
	ReversalOf   sharedkernel.NullID
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertReceipt,
		arg.ID,
		arg.RestaurantID,
		arg.SupplierID,
		arg.Status,
		arg.BusinessDate,
		arg.Note,
		arg.ReversalOf,
	)
	return err
}

const insertRecipeCosting = `-- name: InsertRecipeCosting :exec
INSERT INTO recipe_costings (id, tech_card_id, cost_cents, method, computed_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRecipeCostingParams struct {
	ID         uuid.UUID
	TechCardID uuid.UUID
	CostCents  int64
	Method     string
	ComputedBy uuid.UUID
}

func (q *Queries) InsertRecipeCosting(ctx context.Context, arg InsertRecipeCostingParams) error {
	_, err := q.db.ExecContext(ctx, insertRecipeCosting,
		arg.ID,
		arg.TechCardID,
		arg.CostCents,
		arg.Method,
		arg.ComputedBy,
	)
	return err
}

const insertStockMove = `-- name: InsertStockMove :exec
INSERT INTO stock_moves
    (id, restaurant_id, product_id, kind, qty, cost_cents, estimated, business_date, doc_kind, doc_id, source_event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertStockMoveParams struct {
	ID            uuid.UUID
	RestaurantID  uuid.UUID
	ProductID     uuid.UUID
	Kind          string
	Qty           int64
	CostCents     int64
	Estimated     bool
	BusinessDate  time.Time
	DocKind       string
	DocID         uuid.UUID
	SourceEventID sharedkernel.NullID
}

func (q *Queries) InsertStockMove(ctx context.Context, arg InsertStockMoveParams) error {
	_, err := q.db.ExecContext(ctx, insertStockMove,
		arg.ID,
		arg.RestaurantID,
		arg.ProductID,
		arg.Kind,
		arg.Qty,
		arg.CostCents,
		arg.Estimated,
		arg.BusinessDate,
		arg.DocKind,
		arg.DocID,
		arg.SourceEventID,
	)
	return err
}

const insertSupplier = `-- name: InsertSupplier :exec
INSERT INTO suppliers (id, restaurant_id, name, contacts, note) VALUES ($1, $2, $3, $4, $5)
`

type InsertSupplierParams struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Name         string
	Contacts     json.RawMessage
	Note         string
}

func (q *Queries) InsertSupplier(ctx context.Context, arg InsertSupplierParams) error {
	_, err := q.db.ExecContext(ctx, insertSupplier,
		arg.ID,
		arg.RestaurantID,
		arg.Name,
		arg.Contacts,
		arg.Note,
	)
	return err
}

const insertTechCard = `-- name: InsertTechCard :exec
INSERT INTO tech_cards (id, restaurant_id, product_id, valid_from, valid_to, consumption, yield_milli, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTechCardParams struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
	ValidFrom    time.Time
	ValidTo      sql.NullTime
	Consumption  string
	YieldMilli   int64
	CreatedBy    uuid.UUID
}

func (q *Queries) InsertTechCard(ctx context.Context, arg InsertTechCardParams) error {
	_, err := q.db.ExecContext(ctx, insertTechCard,
		arg.ID,
		arg.RestaurantID,
		arg.ProductID,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Consumption,
		arg.YieldMilli,
		arg.CreatedBy,
	)
	return err
}

const latestCosting = `-- name: LatestCosting :one
SELECT cost_cents FROM recipe_costings WHERE tech_card_id = $1 ORDER BY computed_at DESC LIMIT 1
`

func (q *Queries) LatestCosting(ctx context.Context, techCardID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestCosting, techCardID)
	var cost_cents int64
	err := row.Scan(&cost_cents)
	return cost_cents, err
}

const lockOnHand = `-- name: LockOnHand :one
SELECT restaurant_id, product_id, qty, value_cents, last_avg_cents
FROM stock_on_hand WHERE restaurant_id = $1 AND product_id = $2 FOR UPDATE
`

type LockOnHandParams struct {
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
}

type LockOnHandRow struct {
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
	Qty          int64
	ValueCents   int64
	LastAvgCents int64
}

func (q *Queries) LockOnHand(ctx context.Context, arg LockOnHandParams) (LockOnHandRow, error) {
	row := q.db.QueryRowContext(ctx, lockOnHand, arg.RestaurantID, arg.ProductID)
	var i LockOnHandRow
	err := row.Scan(
		&i.RestaurantID,
		&i.ProductID,
		&i.Qty,
		&i.ValueCents,
		&i.LastAvgCents,
	)
	return i, err
}

const markReceiptPosted = `-- name: MarkReceiptPosted :exec
UPDATE goods_receipts SET status = 'posted', posted_at = now(), posted_by = $3
WHERE restaurant_id = $1 AND id = $2 AND status = 'draft'
`

type MarkReceiptPostedParams struct {
	RestaurantID uuid.UUID
	ID           uuid.UUID
	PostedBy     sharedkernel.NullID
}

func (q *Queries) MarkReceiptPosted(ctx context.Context, arg MarkReceiptPostedParams) error {
	_, err := q.db.ExecContext(ctx, markReceiptPosted, arg.RestaurantID, arg.ID, arg.PostedBy)
	return err
}

const maxMoveDate = `-- name: MaxMoveDate :one
SELECT max(business_date)::date FROM stock_moves WHERE restaurant_id = $1 AND product_id = $2
`

type MaxMoveDateParams struct {
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
}

func (q *Queries) MaxMoveDate(ctx context.Context, arg MaxMoveDateParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, maxMoveDate, arg.RestaurantID, arg.ProductID)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const productByID = `-- name: ProductByID :one
SELECT id, restaurant_id, sku, name, type, stock_unit, menu_item_id, min_stock, archived, created_at
FROM inventory_products WHERE restaurant_id = $1 AND id = $2
`

type ProductByIDParams struct {
	RestaurantID uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) ProductByID(ctx context.Context, arg ProductByIDParams) (InventoryProduct, error) {
	row := q.db.QueryRowContext(ctx, productByID, arg.RestaurantID, arg.ID)
	var i InventoryProduct
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Sku,
		&i.Name,
		&i.Type,
		&i.StockUnit,
		&i.MenuItemID,
		&i.MinStock,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const productHasMoves = `-- name: ProductHasMoves :one
SELECT count(*) FROM stock_moves WHERE product_id = $1
`

func (q *Queries) ProductHasMoves(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, productHasMoves, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const productsByRestaurant = `-- name: ProductsByRestaurant :many
SELECT id, restaurant_id, sku, name, type, stock_unit, menu_item_id, min_stock, archived, created_at
FROM inventory_products WHERE restaurant_id = $1 ORDER BY name
`

func (q *Queries) ProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]InventoryProduct, error) {
	rows, err := q.db.QueryContext(ctx, productsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryProduct
	for rows.Next() {
		var i InventoryProduct
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Sku,
			&i.Name,
			&i.Type,
			&i.StockUnit,
			&i.MenuItemID,
			&i.MinStock,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const techCardLines = `-- name: TechCardLines :many
SELECT id, tech_card_id, ingredient_product_id, qty, seq FROM tech_card_lines
WHERE tech_card_id = $1 ORDER BY seq
`

func (q *Queries) TechCardLines(ctx context.Context, techCardID uuid.UUID) ([]TechCardLine, error) {
	rows, err := q.db.QueryContext(ctx, techCardLines, techCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechCardLine
	for rows.Next() {
		var i TechCardLine
		if err := rows.Scan(
			&i.ID,
			&i.TechCardID,
			&i.IngredientProductID,
			&i.Qty,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOnHand = `-- name: UpsertOnHand :exec
INSERT INTO stock_on_hand (restaurant_id, product_id, qty, value_cents, last_avg_cents, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (restaurant_id, product_id)
DO UPDATE SET qty = EXCLUDED.qty, value_cents = EXCLUDED.value_cents,
              last_avg_cents = EXCLUDED.last_avg_cents, updated_at = now()
`

type UpsertOnHandParams struct {
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
	Qty          int64
	ValueCents   int64
	LastAvgCents int64
}

func (q *Queries) UpsertOnHand(ctx context.Context, arg UpsertOnHandParams) error {
	_, err := q.db.ExecContext(ctx, upsertOnHand,
		arg.RestaurantID,
		arg.ProductID,
		arg.Qty,
		arg.ValueCents,
		arg.LastAvgCents,
	)
	return err
}
