// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inventorydb

import (
	"database/sql"
	"encoding/json"
	"time"

	"aivo/internal/sharedkernel"
	"uuid"
)

type Account struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Code         string
	Name         string
	Type         string
	NormalSide   string
	Postable     bool
	CreatedAt    time.Time
}

type AssistantMessage struct {
	ID           uuid.UUID
	ThreadID     uuid.UUID
	Role         string
	Text         string
	Attachments  json.RawMessage
	Actions      json.RawMessage
	ActionStatus sql.NullString
	CreatedAt    time.Time
}

type AssistantThread struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	CreatedAt    time.Time
}

type CartHandoff struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	CustomerID   sharedkernel.NullID
	Code         string
	Lines        json.RawMessage
	Note         string
	ExpiresAt    time.Time
	UsedAt       sql.NullTime
	CreatedAt    time.Time
}

type CashOperation struct {
	ID           uuid.UUID
	ShiftID      uuid.UUID
	RestaurantID uuid.UUID
	Kind         string
	AmountCents  int64
	Reason       string
	RecordedBy   uuid.UUID
	RecordedAt   time.Time
}

type Category struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Name         string
	Position     int32
	MenuID       uuid.UUID
}

type CostCenter struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Code         string
	Name         string
}

type CustomDomain struct {
	Domain       string
	RestaurantID uuid.UUID
	VerifiedAt   sql.NullTime
	CreatedAt    time.Time
}

type Customer struct {
	ID           uuid.UUID
	Email        string
	PasswordHash []byte
	Name         string
	Phone        sql.NullString
	CreatedAt    time.Time
}

type CustomerSession struct {
	TokenHash  []byte
	CustomerID uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type Event struct {
	ID            uuid.UUID
	Name          string
	AggregateType string
	AggregateID   uuid.UUID
	RestaurantID  sharedkernel.NullID
	Payload       json.RawMessage
	OccurredAt    time.Time
	PublishedAt   sql.NullTime
}

type GoodsReceipt struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	SupplierID   sharedkernel.NullID
	Status       string
	BusinessDate time.Time
	Note         string
	PostedAt     sql.NullTime
	PostedBy     sharedkernel.NullID
	ReversalOf   sharedkernel.NullID
	CreatedAt    time.Time
}

type GoodsReceiptLine struct {
	ID             uuid.UUID
	ReceiptID      uuid.UUID
	ProductID      uuid.UUID
	QtyBaseMilli   int64
	InputUnit      string
	UnitPriceCents int64
	LineCostCents  int64
	Seq            int32
}

type GuestProfile struct {
	RestaurantID uuid.UUID
	CustomerID   uuid.UUID
	Notes        string
	Tags         json.RawMessage
	FirstSeen    time.Time
	LastSeen     time.Time
}

type InventoryProduct struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Sku          string
	Name         string
	Type         string
	StockUnit    string
	MenuItemID   sharedkernel.NullID
	MinStock     sql.NullInt64
	Archived     bool
	CreatedAt    time.Time
}

type JournalDocument struct {
	ID             uuid.UUID
	RestaurantID   uuid.UUID
	Kind           string
	State          string
	AccountingDate time.Time
	RecordedAt     time.Time
	PostedAt       sql.NullTime
	CancelledAt    sql.NullTime
	SourceKind     sql.NullString
	SourceID       sharedkernel.NullID
	ReversalOf     sharedkernel.NullID
	CreatedBy      uuid.UUID
}

type JournalLine struct {
	ID           uuid.UUID
	DocumentID   uuid.UUID
	AccountID    uuid.UUID
	Side         string
	AmountCents  int64
	CostCenterID uuid.UUID
	Memo         string
	Seq          int32
}

type LandingBlock struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Type         string
	Position     int32
	Data         json.RawMessage
}

type LedgerAccountMap struct {
	RestaurantID uuid.UUID
	Purpose      string
	AccountID    uuid.UUID
}

type Menu struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Slug         string
	Name         string
	Position     int32
	IsDefault    bool
}

type MenuItem struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	CategoryID   uuid.UUID
	Name         string
	Description  string
	PriceCents   int32
	ImageUrl     string
	Available    bool
}

type MenuItemAllergen struct {
	MenuItemID uuid.UUID
	Allergen   string
}

type NotificationChannel struct {
	RestaurantID      uuid.UUID
	TelegramChatID    string
	EncryptedBotToken []byte
	KeyVersion        int32
}

type Option struct {
	ID              uuid.UUID
	OptionGroupID   uuid.UUID
	Label           string
	PriceDeltaCents int32
	Position        int32
}

type OptionGroup struct {
	ID         uuid.UUID
	MenuItemID uuid.UUID
	Name       string
	Multi      bool
	Position   int32
}

type Order struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	Comment      string
	CreatedAt    time.Time
	CustomerID   sharedkernel.NullID
}

type OrderLine struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	MenuItemID     uuid.UUID
	Name           string
	UnitPriceCents int32
	Qty            int32
}

type OrderLineOption struct {
	ID              uuid.UUID
	OrderLineID     uuid.UUID
	Label           string
	PriceDeltaCents int32
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type PaymentMethod struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Code         string
	Name         string
	PaymentGroup string
	Active       bool
}

type RecipeCosting struct {
	ID         uuid.UUID
	TechCardID uuid.UUID
	CostCents  int64
	Method     string
	ComputedAt time.Time
	ComputedBy uuid.UUID
}

type Restaurant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
	OrgID     sharedkernel.NullID
	Address   string
	Hours     json.RawMessage
	Contacts  json.RawMessage
}

type RestaurantTheme struct {
	RestaurantID uuid.UUID
	Theme        json.RawMessage
	DesignMd     string
	UpdatedAt    time.Time
}

type ServiceRequest struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	Kind         string
	Status       string
	CreatedAt    time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Shift struct {
	ID                uuid.UUID
	RestaurantID      uuid.UUID
	OpenedBy          uuid.UUID
	OpenedAt          time.Time
	OpeningFloatCents int32
	ClosedAt          sql.NullTime
	DeclaredCents     sql.NullInt32
	ExpectedCents     sql.NullInt32
	VarianceCents     sql.NullInt32
	Cashier           string
	AcceptedAt        sql.NullTime
	AcceptedBy        sharedkernel.NullID
	JournalDocumentID sharedkernel.NullID
}

type StockMove struct {
	ID            uuid.UUID
	RestaurantID  uuid.UUID
	ProductID     uuid.UUID
	Kind          string
	Qty           int64
	CostCents     int64
	Estimated     bool
	BusinessDate  time.Time
	RecordedAt    time.Time
	DocKind       string
	DocID         uuid.UUID
	SourceEventID sharedkernel.NullID
	CreatedAt     time.Time
}

type StockOnHand struct {
	RestaurantID uuid.UUID
	ProductID    uuid.UUID
	Qty          int64
	ValueCents   int64
	LastAvgCents int64
	UpdatedAt    time.Time
}

type Stocktake struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Status       string
	BusinessDate time.Time
	Note         string
	PostedAt     sql.NullTime
	PostedBy     sharedkernel.NullID
	ReversalOf   sharedkernel.NullID
	CreatedAt    time.Time
}

type StocktakeLine struct {
	ID                uuid.UUID
	StocktakeID       uuid.UUID
	ProductID         uuid.UUID
	CountedQtyMilli   int64
	ExpectedQtyMilli  sql.NullInt64
	VarianceQtyMilli  int64
	VarianceCostCents int64
	Seq               int32
}

type Subscription struct {
	OrgID     uuid.UUID
	Plan      string
	Status    string
	UpdatedAt time.Time
}

type Supplier struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Name         string
	Contacts     json.RawMessage
	Note         string
	Archived     bool
	CreatedAt    time.Time
}

type Table struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Label        string
	Token        string
	CreatedAt    time.Time
}

type TechCard struct {
	ID               uuid.UUID
	RestaurantID     uuid.UUID
	ProductID        uuid.UUID
	ValidFrom        time.Time
	ValidTo          sql.NullTime
	Consumption      string
	YieldMilli       int64
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
	Format           string
	ScopeNote        sql.NullString
	PresentationNote sql.NullString
	StorageNote      sql.NullString
	OrganolepticNote sql.NullString
}

type TechCardLine struct {
	ID                  uuid.UUID
	TechCardID          uuid.UUID
	IngredientProductID uuid.UUID
	Qty                 int64
	Seq                 int32
	YieldPermille       int32
}

type Ticket struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	ShiftID      uuid.UUID
	TableID      uuid.UUID
	Status       string
	CreatedAt    time.Time
	Note         string
	CustomerID   sharedkernel.NullID
	ClosedAt     sql.NullTime
}

type TicketLine struct {
	ID             uuid.UUID
	TicketID       uuid.UUID
	MenuItemID     uuid.UUID
	Name           string
	UnitPriceCents int32
	Qty            int32
	Options        json.RawMessage
	FiredAt        sql.NullTime
	CreatedAt      time.Time
}

type TicketPayment struct {
	ID           uuid.UUID
	TicketID     uuid.UUID
	RestaurantID uuid.UUID
	MethodID     uuid.UUID
	PaymentGroup string
	AmountCents  int64
	TipCents     int64
	RecordedAt   time.Time
	RecordedBy   uuid.UUID
}

type User struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Email        string
	PasswordHash []byte
	Role         string
	RestaurantID sharedkernel.NullID
	CreatedAt    time.Time
}

type WriteOff struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Reason       string
	Status       string
	BusinessDate time.Time
	Note         string
	PostedAt     sql.NullTime
	PostedBy     sharedkernel.NullID
	ReversalOf   sharedkernel.NullID
	CreatedAt    time.Time
}

type WriteOffLine struct {
	ID           uuid.UUID
	WriteOffID   uuid.UUID
	ProductID    uuid.UUID
	QtyBaseMilli int64
	InputUnit    string
	Seq          int32
}
