// inventory-service capability (see openspec/changes/split-inventory-microservice).
//
// Written by the inventory worktree since it was not present when this
// worktree started (tasks.md 3.2) — svc-server's ticket-close client
// needs this shape to compile against; reconcile at merge if svc-server
// independently authored a conflicting version.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaleLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    string                 `protobuf:"bytes,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"` // uuid
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	TicketLineId  string                 `protobuf:"bytes,3,opt,name=ticket_line_id,json=ticketLineId,proto3" json:"ticket_line_id,omitempty"` // uuid; used with menu_item_id to derive per-line idempotency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleLine) Reset() {
	*x = SaleLine{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleLine) ProtoMessage() {}

func (x *SaleLine) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleLine.ProtoReflect.Descriptor instead.
func (*SaleLine) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *SaleLine) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *SaleLine) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *SaleLine) GetTicketLineId() string {
	if x != nil {
		return x.TicketLineId
	}
	return ""
}

type HandleTicketClosedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"` // uuid; tenant scope
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`             // uuid; idempotency key (source_document_id)
	ClosedBy      string                 `protobuf:"bytes,3,opt,name=closed_by,json=closedBy,proto3" json:"closed_by,omitempty"`             // uuid
	BusinessDate  string                 `protobuf:"bytes,4,opt,name=business_date,json=businessDate,proto3" json:"business_date,omitempty"` // YYYY-MM-DD
	Lines         []*SaleLine            `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTicketClosedRequest) Reset() {
	*x = HandleTicketClosedRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTicketClosedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTicketClosedRequest) ProtoMessage() {}

func (x *HandleTicketClosedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTicketClosedRequest.ProtoReflect.Descriptor instead.
func (*HandleTicketClosedRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *HandleTicketClosedRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *HandleTicketClosedRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *HandleTicketClosedRequest) GetClosedBy() string {
	if x != nil {
		return x.ClosedBy
	}
	return ""
}

func (x *HandleTicketClosedRequest) GetBusinessDate() string {
	if x != nil {
		return x.BusinessDate
	}
	return ""
}

func (x *HandleTicketClosedRequest) GetLines() []*SaleLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type HandleTicketClosedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"` // false when this ticket_id was already processed (no-op redelivery)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTicketClosedResponse) Reset() {
	*x = HandleTicketClosedResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTicketClosedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTicketClosedResponse) ProtoMessage() {}

func (x *HandleTicketClosedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTicketClosedResponse.ProtoReflect.Descriptor instead.
func (*HandleTicketClosedResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *HandleTicketClosedResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\"d\n" +
	"\bSaleLine\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\tR\n" +
	"menuItemId\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\x12$\n" +
	"\x0eticket_line_id\x18\x03 \x01(\tR\fticketLineId\"\xcd\x01\n" +
	"\x19HandleTicketClosedRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x1b\n" +
	"\tclosed_by\x18\x03 \x01(\tR\bclosedBy\x12#\n" +
	"\rbusiness_date\x18\x04 \x01(\tR\fbusinessDate\x12,\n" +
	"\x05lines\x18\x05 \x03(\v2\x16.inventory.v1.SaleLineR\x05lines\"6\n" +
	"\x1aHandleTicketClosedResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied2{\n" +
	"\x10InventoryService\x12g\n" +
	"\x12HandleTicketClosed\x12'.inventory.v1.HandleTicketClosedRequest\x1a(.inventory.v1.HandleTicketClosedResponseB(Z&aivo/internal/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*SaleLine)(nil),                   // 0: inventory.v1.SaleLine
	(*HandleTicketClosedRequest)(nil),  // 1: inventory.v1.HandleTicketClosedRequest
	(*HandleTicketClosedResponse)(nil), // 2: inventory.v1.HandleTicketClosedResponse
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.HandleTicketClosedRequest.lines:type_name -> inventory.v1.SaleLine
	1, // 1: inventory.v1.InventoryService.HandleTicketClosed:input_type -> inventory.v1.HandleTicketClosedRequest
	2, // 2: inventory.v1.InventoryService.HandleTicketClosed:output_type -> inventory.v1.HandleTicketClosedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
