// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package posdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AssistantMessage struct {
	ID           uuid.UUID
	ThreadID     uuid.UUID
	Role         string
	Text         string
	Attachments  json.RawMessage
	Actions      json.RawMessage
	ActionStatus sql.NullString
	CreatedAt    time.Time
}

type AssistantThread struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	CreatedAt    time.Time
}

type CartHandoff struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	CustomerID   uuid.NullUUID
	Code         string
	Lines        json.RawMessage
	Note         string
	ExpiresAt    time.Time
	UsedAt       sql.NullTime
	CreatedAt    time.Time
}

type Category struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Name         string
	Position     int32
	MenuID       uuid.UUID
}

type CustomDomain struct {
	Domain       string
	RestaurantID uuid.UUID
	VerifiedAt   sql.NullTime
	CreatedAt    time.Time
}

type Customer struct {
	ID           uuid.UUID
	Email        string
	PasswordHash []byte
	Name         string
	Phone        sql.NullString
	CreatedAt    time.Time
}

type CustomerSession struct {
	TokenHash  []byte
	CustomerID uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type Event struct {
	ID            uuid.UUID
	Name          string
	AggregateType string
	AggregateID   uuid.UUID
	RestaurantID  uuid.NullUUID
	Payload       json.RawMessage
	OccurredAt    time.Time
	PublishedAt   sql.NullTime
}

type GuestProfile struct {
	RestaurantID uuid.UUID
	CustomerID   uuid.UUID
	Notes        string
	Tags         json.RawMessage
	FirstSeen    time.Time
	LastSeen     time.Time
}

type LandingBlock struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Type         string
	Position     int32
	Data         json.RawMessage
}

type Menu struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Slug         string
	Name         string
	Position     int32
	IsDefault    bool
}

type MenuItem struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	CategoryID   uuid.UUID
	Name         string
	Description  string
	PriceCents   int32
	ImageUrl     string
	Available    bool
}

type MenuItemAllergen struct {
	MenuItemID uuid.UUID
	Allergen   string
}

type NotificationChannel struct {
	RestaurantID      uuid.UUID
	TelegramChatID    string
	EncryptedBotToken []byte
	KeyVersion        int32
}

type Option struct {
	ID              uuid.UUID
	OptionGroupID   uuid.UUID
	Label           string
	PriceDeltaCents int32
	Position        int32
}

type OptionGroup struct {
	ID         uuid.UUID
	MenuItemID uuid.UUID
	Name       string
	Multi      bool
	Position   int32
}

type Order struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	Comment      string
	CreatedAt    time.Time
	CustomerID   uuid.NullUUID
}

type OrderLine struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	MenuItemID     uuid.UUID
	Name           string
	UnitPriceCents int32
	Qty            int32
}

type OrderLineOption struct {
	ID              uuid.UUID
	OrderLineID     uuid.UUID
	Label           string
	PriceDeltaCents int32
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Restaurant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
	OrgID     uuid.NullUUID
	Address   string
	Hours     json.RawMessage
	Contacts  json.RawMessage
}

type RestaurantTheme struct {
	RestaurantID uuid.UUID
	Theme        json.RawMessage
	DesignMd     string
	UpdatedAt    time.Time
}

type ServiceRequest struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	Kind         string
	Status       string
	CreatedAt    time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Shift struct {
	ID                uuid.UUID
	RestaurantID      uuid.UUID
	OpenedBy          uuid.UUID
	OpenedAt          time.Time
	OpeningFloatCents int32
	ClosedAt          sql.NullTime
	DeclaredCents     sql.NullInt32
	ExpectedCents     sql.NullInt32
	VarianceCents     sql.NullInt32
	Cashier           string
}

type Subscription struct {
	OrgID     uuid.UUID
	Plan      string
	Status    string
	UpdatedAt time.Time
}

type Table struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Label        string
	Token        string
	CreatedAt    time.Time
}

type Ticket struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	ShiftID      uuid.UUID
	TableID      uuid.UUID
	Status       string
	CreatedAt    time.Time
	Note         string
	CustomerID   uuid.NullUUID
}

type TicketLine struct {
	ID             uuid.UUID
	TicketID       uuid.UUID
	MenuItemID     uuid.UUID
	Name           string
	UnitPriceCents int32
	Qty            int32
	Options        json.RawMessage
	FiredAt        sql.NullTime
	CreatedAt      time.Time
}

type User struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Email        string
	PasswordHash []byte
	Role         string
	RestaurantID uuid.NullUUID
	CreatedAt    time.Time
}
