// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pos.sql

package posdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const openShiftByRestaurant = `-- name: OpenShiftByRestaurant :one
SELECT id, restaurant_id, opened_by, opened_at, opening_float_cents, cashier
FROM shifts WHERE restaurant_id = $1 AND closed_at IS NULL
`

type OpenShiftByRestaurantRow struct {
	ID                uuid.UUID
	RestaurantID      uuid.UUID
	OpenedBy          uuid.UUID
	OpenedAt          time.Time
	OpeningFloatCents int32
	Cashier           string
}

func (q *Queries) OpenShiftByRestaurant(ctx context.Context, restaurantID uuid.UUID) (OpenShiftByRestaurantRow, error) {
	row := q.db.QueryRowContext(ctx, openShiftByRestaurant, restaurantID)
	var i OpenShiftByRestaurantRow
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.OpeningFloatCents,
		&i.Cashier,
	)
	return i, err
}

const openTickets = `-- name: OpenTickets :many
SELECT id, shift_id, table_id, status, note, created_at
FROM tickets WHERE restaurant_id = $1 AND status = 'open' ORDER BY created_at
`

type OpenTicketsRow struct {
	ID        uuid.UUID
	ShiftID   uuid.UUID
	TableID   uuid.UUID
	Status    string
	Note      string
	CreatedAt time.Time
}

func (q *Queries) OpenTickets(ctx context.Context, restaurantID uuid.UUID) ([]OpenTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, openTickets, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenTicketsRow
	for rows.Next() {
		var i OpenTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShiftID,
			&i.TableID,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
