// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package menudb

import (
	"context"

	"uuid"
)

const categoriesByMenu = `-- name: CategoriesByMenu :many
SELECT id, restaurant_id, menu_id, name, position
FROM categories WHERE menu_id = $1 ORDER BY position
`

type CategoriesByMenuRow struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	MenuID       uuid.UUID
	Name         string
	Position     int32
}

func (q *Queries) CategoriesByMenu(ctx context.Context, menuID uuid.UUID) ([]CategoriesByMenuRow, error) {
	rows, err := q.db.QueryContext(ctx, categoriesByMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriesByMenuRow
	for rows.Next() {
		var i CategoriesByMenuRow
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.MenuID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemsByCategory = `-- name: ItemsByCategory :many
SELECT id, category_id, name, description, price_cents, image_url, available
FROM menu_items WHERE category_id = $1
`

type ItemsByCategoryRow struct {
	ID          uuid.UUID
	CategoryID  uuid.UUID
	Name        string
	Description string
	PriceCents  int32
	ImageUrl    string
	Available   bool
}

func (q *Queries) ItemsByCategory(ctx context.Context, categoryID uuid.UUID) ([]ItemsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, itemsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemsByCategoryRow
	for rows.Next() {
		var i ItemsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.ImageUrl,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menusByRestaurant = `-- name: MenusByRestaurant :many
SELECT id, restaurant_id, slug, name, position, is_default
FROM menus WHERE restaurant_id = $1 ORDER BY position
`

func (q *Queries) MenusByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, menusByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Slug,
			&i.Name,
			&i.Position,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restaurantBySlug = `-- name: RestaurantBySlug :one
SELECT id, slug, name FROM restaurants WHERE slug = $1
`

type RestaurantBySlugRow struct {
	ID   uuid.UUID
	Slug string
	Name string
}

func (q *Queries) RestaurantBySlug(ctx context.Context, slug string) (RestaurantBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, restaurantBySlug, slug)
	var i RestaurantBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}
