// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package menudb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CartHandoff struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	CustomerID   uuid.NullUUID
	Code         string
	Lines        json.RawMessage
	Note         string
	ExpiresAt    time.Time
	UsedAt       sql.NullTime
	CreatedAt    time.Time
}

type Category struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Name         string
	Position     int32
	MenuID       uuid.UUID
}

type LandingBlock struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Type         string
	Position     int32
	Data         json.RawMessage
}

type Menu struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Slug         string
	Name         string
	Position     int32
	IsDefault    bool
}

type MenuItem struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	CategoryID   uuid.UUID
	Name         string
	Description  string
	PriceCents   int32
	ImageUrl     string
	Available    bool
}

type MenuItemAllergen struct {
	MenuItemID uuid.UUID
	Allergen   string
}

type NotificationChannel struct {
	RestaurantID      uuid.UUID
	TelegramChatID    string
	EncryptedBotToken []byte
	KeyVersion        int32
}

type Option struct {
	ID              uuid.UUID
	OptionGroupID   uuid.UUID
	Label           string
	PriceDeltaCents int32
	Position        int32
}

type OptionGroup struct {
	ID         uuid.UUID
	MenuItemID uuid.UUID
	Name       string
	Multi      bool
	Position   int32
}

type Order struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	Comment      string
	CreatedAt    time.Time
	CustomerID   uuid.NullUUID
}

type OrderLine struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	MenuItemID     uuid.UUID
	Name           string
	UnitPriceCents int32
	Qty            int32
}

type OrderLineOption struct {
	ID              uuid.UUID
	OrderLineID     uuid.UUID
	Label           string
	PriceDeltaCents int32
}

type Restaurant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
}

type ServiceRequest struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	TableID      uuid.UUID
	Kind         string
	Status       string
	CreatedAt    time.Time
}

type Table struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Label        string
	Token        string
	CreatedAt    time.Time
}
